site_name: Keras中文文档
r"pages":
- ['index.md','主页']
- ['for_beginners/concepts.md','keras新手指南','一些基本概念']
- ['for_beginners/FAQ.md','keras新手指南','常见问题与解答']
- ['for_beginners/keras_linux.md','keras新手指南','Keras安装和配置指南(Linux)']
- ['for_beginners/keras_windows.md','keras新手指南','Keras安装和配置指南(Windows)']
- ['for_beginners/trap.md','keras新手指南','Keras使用陷阱']
- ['getting_started/sequential_model.md','快速开始','序贯模型']
- ['getting_started/functional_API.md','快速开始','函数式模型']
- ['models/about_model.md','模型','关于Keras模型']
- ['models/sequential.md','模型','序贯模型API']
- ['models/model.md','模型','函数式模型API']
- ['layers/about_layer.md','网络层','关于Keras层']
- ['layers/core_layer.md','网络层','常用层Core']
- ['layers/convolutional_layer.md','网络层','卷积层Convolutional']
- ['layers/pooling_layer.md','网络层','池化层Pooling']
- ['layers/locally_connected_layer.md','网络层','局部连接层Locally-connented']
- ['layers/recurrent_layer.md','网络层','循环层Recurrent']
- ['layers/embedding_layer.md','网络层','嵌入层Embedding']
- ['layers/merge.md','网络层','融合层Merge']
- ['layers/advanced_activation_layer.md','网络层','高级激活层Advanced Activation']
- ['layers/normalization_layer.md','网络层','规范层BatchNormalization']
- ['layers/noise_layer.md','网络层','噪声层Noise']
- ['layers/wrapper.md','网络层','包装器Wrapper']
- ['layers/writting_layer.md','网络层','编写自己的层']
- ['preprocessing/sequence.md','数据预处理','序列预处理']
- ['preprocessing/text.md','数据预处理','文本预处理']
- ['preprocessing/image.md','数据预处理','图片预处理']
- ['other/objectives.md','网络配置','损失函数loss']
- ['other/optimizers.md','网络配置','优化器Optimizer']
- ['other/activations.md','网络配置','激活函数Activation']
- ['other/metrics.md','网络配置','性能评估Metrices']
- ['other/initializations.md','网络配置','初始化方法Initializers']
- ['other/regularizers.md','网络配置','正则项Regularizer']
- ['other/constraints.md','网络配置','约束项Constraint']
- ['other/callbacks.md','网络配置','回调函数Callback']
- ['other/application.md','协助使用Keras','预训练模型Application']
- ['other/datasets.md','协助使用Keras','常用数据库Dataset']
- ['other/visualization.md','协助使用Keras','可视化visualization']
- ['utils.md','协助使用Keras','工具']
- ['backend.md','keras后端Backend']
- ['scikit-learn_API.md','scikit-learn接口']
- ['acknowledgement.md','致谢']
theme: readthedocs
site_author: BigMoyan
